### ISSUE TITLE
Build Against Anaconda Python?

### ISSUE THREAD

**Issue by jlaura** [commontk/PythonQt#24] opened 2015-08-04 14:25 UTC
I am trying to build PythonQt against anaconda python (2.7.x). Running the included PyGuiExample I am unable to get any Python other than the system install.

Running OS X 10.10, Qt 5.5, latest Anaconda.

I have set the python.prf as

```
PYTHON_CONFIG_PATH = /Users/me/anaconda/bin/python-config
QMAKE_CXXFLAGS += $$system($${PYTHON_CONFIG_PATH} --includes)
LIBS += $$system($${PYTHON_CONFIG_PATH} --libs)
```

Two environment variables have been set

```
PYTHON_PATH /Users/me/anaconda/include/python2.7
PYTHON_LIB /Users/me/anaconda/lib
```

The build (in QtCreator) is successful with a high number of warnings about unused parameters.

Any thoughts on getting PythonQt built against a Python installation other than the system framework?

**Comment by jcfr** [comment] 2015-08-04 14:34
Hi @jlaura , 

Thanks for reaching out.

Since the PythonQt fork we maintain in the commontk organization is not (yet) updated against the latest version of the official PythonQt source tree available on sourceforge. I would suggest you try with the most recent sources. 

See:
- http://pythonqt.sourceforge.net/
- http://sourceforge.net/p/pythonqt/code/HEAD/tree/trunk/

Note that we created this work as a staging area for improvement to CMake buildsystem of PythonQt before we contribute them upstream.

On a related note, in the coming week, we will also be working on experimental support for miniconda/anaconda for [3DSlicer](http://slicer.org) (and by extension [CTK](http://commontk.org)). 

Some details are reported here http://wiki.slicer.org/slicerWiki/index.php/Documentation/Labs/PythonCondaBuild

Let me know if you have any questions, 

Thanks
Jc

**Comment by jlaura** [comment] 2015-08-04 14:44
Thanks for the heads up.  I have posted to the source forge discussion site.  Would you rather keep this issue open pending a response from upstream or close?

**Comment by patmarion** [comment] 2015-08-04 14:49
I think the issue is with CMake's FindPythonLibs.cmake script.  It finds the correct Python interpreter but not the correct lib and headers.  In order to correctly find homebrew python on mac, I use cmake code like this:

(note, this isn't totally general, but it works well enough for me for python 2.7):

<pre>
if(APPLE)
  find_program(PYTHON_CONFIG_EXECUTABLE python-config)
  if (NOT PYTHON_CONFIG_EXECUTABLE)
    message(SEND_ERROR "python-config executable not found, but python is required.")
  endif()
  # using "python-config --prefix" so that cmake always uses the python that is
  # in the user's path, this is a fix for homebrew on Mac:
  # https://github.com/Homebrew/homebrew/issues/25118
  execute_process(COMMAND ${PYTHON_CONFIG_EXECUTABLE} --prefix OUTPUT_VARIABLE python_prefix OUTPUT_STRIP_TRAILING_WHITESPACE)
  set(PYTHON_INCLUDE_DIR ${python_prefix}/include/python2.7)
  set(PYTHON_LIBRARY ${python_prefix}/lib/libpython2.7${CMAKE_SHARED_LIBRARY_SUFFIX})
endif()
find_package(PythonLibs 2.7 REQUIRED)
</pre>

**Comment by jcfr** [comment] 2015-08-05 01:12
@jlaura Let's close this issue. For reference, here is the associated post on PythonQt forum: http://sourceforge.net/p/pythonqt/discussion/631393/thread/bc3b8e92/?limit=25#2f9b

@patmarion Thanks for the note. I added a note to the associated CMake issue. See http://www.cmake.org/Bug/view.php?id=14809#c39236

**Closed as completed by jcfr** 2015-08-05 01:12 UTC
